guest = ['Jack','John','Tom','Tony','Eric']
print("I wound like to invite you to have dinner with me, "+guest[0])
print("I wound like to invite you to have dinner with me, "+guest[1])
print("I wound like to invite you to have dinner with me, "+guest[2])
print("I wound like to invite you to have dinner with me, "+guest[3])
print("I wound like to invite you to have dinner with me, "+guest[4])
print("I have found a bigger room.")
guest.insert(0,'Sony')
guest.insert(3,'Jimmy')
guest.append('Alex')
print("I wound like to invite you to have dinner with me, "+guest[0])
print("I wound like to invite you to have dinner with me, "+guest[1])
print("I wound like to invite you to have dinner with me, "+guest[2])
print("I wound like to invite you to have dinner with me, "+guest[3])
print("I wound like to invite you to have dinner with me, "+guest[4])
print("I wound like to invite you to have dinner with me, "+guest[5])
print("I wound like to invite you to have dinner with me, "+guest[6])
print("I wound like to invite you to have dinner with me, "+guest[7])